### ISSUE TITLE
Intro to redux

### ISSUE THREAD

**Issue by cherta** [montevideojs/meetups#5]
Quiero mostrar en una charla corta los conceptos de redux y las nuevas formas de desarrollo que habilita:

* Qué es redux y para qué sirve
* Los tres pilares de redux
 * Single state tree
 * Read only state
 * Reducers and pure functions
* Redux y React
 * Cómo se complementan
 * `connect`ando componentes
 * Herramientas: Hot Reloading & Redux DevTool
* Aplicaciones en el mundo real (menciones)
 * Thunk middleware
 * Redux Router & Simple Redux Router
 * Ecosistema en gral

Me parece que si bien redux es difícil de entender al principio los conceptos son muy simples cuando se lo desconecta de React, webpack y el ecosistema React en gral, eso es lo que pretendo hacer.

Algunas ppt's y mucho JSBin con conceptos simples para al final si mostrar una app local que tenga thunk, router, dev tools etc como para dejarla picando.

Acepto sugerencias.

**Comment by PabloSuarez** [comment]
Buena @cherta !!

**Comment by cherta** [comment]
Gracias @PabloSuarez!

**Comment by nachoaIvarez** [comment]
Estaba viniendo a hacer un pull request para dar esta misma charla. Todo mal con vos @cherta.

**Comment by cherta** [comment]
La damos juntos si querés @nachoaIvarez ;)

**Comment by pricco** [comment]
:+1:

**Comment by nachoaIvarez** [comment]
Me va! Eligí qué querés dar, y yo agarro lo que sobre, dado que vos llegaste primero. La otra que se me ocurre es hacer un "teórico" (la charla que vos sugeriste) y un "práctico" (construir una app react+redux).

**Comment by cherta** [comment]
Es buena! Armé un [repo](https://github.com/cherta/redux-talk) y te dejé como colaborador para que vayas agregando a ese README.

**Comment by francocorreasosa** [comment]
Me viene de 10 esta charla :+1:

**Comment by pricco** [comment]
Me pasan Titulo y Descripción? Van a dar teorico y practico? Por ahora están los dos slots libres

**Comment by cherta** [comment]
Creo que se pueden dar los dos @pricco, hay que ver si @nachoaIvarez se cuelga. Yo pensaba dar un teórico mostrando jsbin's

**Comment by pricco** [comment]
@cherta y @nachoaIvarez tengo que publicar la charla hoy sin falta.
Me pasan titulo, descripción y duración. Gracias

**Comment by nachoaIvarez** [comment]
Claro! Yo hago una demo de full-stack redux. Como puse [acá](https://github.com/cherta/redux-talk/blob/master/README.md): _Using redux and socket.io to build a real time app featuring redux both in back end and the front end._

**Comment by cherta** [comment]
Y yo hago una con el nombre que puse al principio en el ticket y quedan
enganchadas ;)
